{% set name = "databricks-cli" %}
{% set version = "0.273.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/databricks/cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 76b418de3baca43cbb851a8a215dc26d6344c3d22916287d726e0baf6ebe6d13

build:
  number: 0
  script_env:
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks      # [not win]
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks.exe  # [win]

requirements:
  build:
    - {{ compiler('go') }} >=1.24.1
    - go-licenses
    - posix                  # [win]

test:
  requires:
    - ripgrep
  commands:
    - databricks --help
    - databricks --version | rg {{ version }}

about:
  summary: A command line interface for Databricks
  home: https://github.com/databricks/cli
  license: LicenseRef-Databricks-License
  license_file:
    - LICENSE
    - NOTICE
    - thirdparty/

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute
    - dhirschfeld
