{% set name = "databricks-cli" %}
{% set version = "0.299.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/databricks/cli/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b5a3d46ed9cf5dad0d0e053126b8d15fc86fc2835e1436cc07579631928eb3f7
  - url: https://raw.githubusercontent.com/mattn/go-localereader/refs/heads/master/LICENSE  # [win]
    sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3  # [win]
    fn: LICENSE-go-localereader  # [win]


build:
  number: 0
  script_env:
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks      # [not win]
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks.exe  # [win]

requirements:
  build:
    - {{ compiler('go') }} >=1.24.1
    - go-licenses
    - m2-base                  # [win]

test:
  requires:
    - ripgrep
  commands:
    - databricks --help
    - databricks --version | rg {{ version }}

about:
  summary: A command line interface for Databricks
  home: https://github.com/databricks/cli
  license: LicenseRef-Databricks-License
  license_file:
    - LICENSE
    - NOTICE
    - thirdparty/
    - LICENSE-go-localereader  # [win]

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute
    - dhirschfeld
