{% set name = "databricks-cli" %}
{% set version = "0.231.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/databricks/cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3fa83b434ca9ecd8e9ef77cffe67f4ca005a2de8af29861f145184a89086bc05

build:
  number: 0
  script_env:
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks      # [not win]
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks.exe  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
    - posix                  # [win]

test:
  requires:
    - ripgrep
  commands:
    - databricks --help
    - databricks --version | rg {{ version }}

about:
  summary: A command line interface for Databricks
  home: https://github.com/databricks/cli
  license: LicenseRef-Databricks-License
  license_file:
    - LICENSE
    - NOTICE
    - thirdparty/

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute
    - dhirschfeld
